config/routes.rb
Rails.application.routes.draw do
  resources :sites, only: :index
  resources :blog, as: :blog, only: [:index, :show]
  resources :messages, only: :create

  namespace :admin do
    resources :sites, except: [:index, :show] do
      collection { post :sort }
    end
    resources :blog, as: :blog, except: [:index, :show]
    root to: 'base#index'
  end

  get '/sitemap', to: 'sites#sitemap', defaults: { format: :xml }

  root to: 'sites#index'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  default_scope { order('created_at desc') }
  scope :public_posts, -> { where(private: false) }

  def next
    Blog.unscoped.public_posts.where('id > ?', self.id).order('created_at asc').first
  end

  def previous
    Blog.public_posts.where('id < ?', self.id).first
  end
end

app/models/message.rb
class Message < ActiveRecord::Base

  after_create :send_email_to_ryan

  validates_presence_of :name, :email, :body

  default_scope { order('created_at desc') }

  private

  def send_email_to_ryan
    SitesMailer.contact_form(name, email, body).deliver
  end
end

app/models/site.rb
class Site < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :photo, styles: { list: "584x326#" },
                            storage: :s3, s3_credentials: "#{Rails.root}/config/s3.yml",
                            path: ':id/:style', s3_host_alias: 'assets.goddamnyouryan.com',
                            url: ':s3_alias_url'
  validates_attachment_content_type :photo, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  scope :ordered, -> { order('position') }
  scope :active, -> { where(status: 'active').ordered }
  scope :inactive, -> { where(status: 'inactive').ordered }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :password_protect
  layout 'admin'

  def index
    @sites = Site.active
    @inactive = Site.inactive
    @blog = Blog.all
    @messages = Message.all
  end

  private

  def password_protect
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'ryan' && password == ENV['GODDAMNYOURYAN_ADMIN_PASSWORD']
    end
  end
end

app/controllers/admin/blog_controller.rb
class Admin::BlogController < Admin::BaseController
  before_filter :find_blog, only: [:edit, :update, :destroy]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new blog_params
    if @blog.save
      redirect_to @blog, notice: 'Blog post created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @blog.update_attributes blog_params
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy
    @title = @blog.title
    @blog.destroy

    redirect_to admin_root_path, notice: "#{@title} deleted"
  end

  private

  def blog_params
    params.require(:blog).permit(:body, :title, :private, :title_image, :dark)
  end
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < Admin::BaseController
  before_filter :find_site, only: [:edit, :update, :destroy]

  def new
    @site = Site.new
  end

  def create
    @site = Site.new site_params
    if @site.save
      redirect_to admin_root_path
    else
      redirect_to new_site_path
    end
  end

  def edit
  end

  def update
    if params[:status]
      @site.update_attributes(status: params[:status])
    else
      @site.update_attributes site_params
    end

    redirect_to admin_root_path, notice: "#{@site.name} updated."
  end

  def destroy
    @site.destroy
    redirect_to admin_root_path, notice: "#{@site.name} deleted."
  end

  def sort
    params[:site].each_with_index do |id, index|
      Site.find(id).update_attribute :position, index + 1
    end
    render nothing: true
  end

  private

  def find_site
    @site = Site.friendly.find params[:id]
  end

  def site_params
    params.require(:site).permit(:description, :name, :order, :status, :url, :photo, :background_color, :text_color, :dark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def find_blog
    @blog = Blog.friendly.find params[:id]
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_filter :find_blog, only: :show
  layout 'blog'

  def index
    @blog = Blog.public_posts.first
    @blogs = Blog.public_posts
    @previous = @blog.previous
    @next = @blog.next
    respond_to do |format|
      format.html { render :show }
      format.rss
    end
  end

  def show
    @previous = @blog.previous
    @next = @blog.next
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.create message_params
    respond_to do |format|
      format.js
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :email, :name)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  http_basic_authenticate_with name: 'ryan', password: ENV['GODDAMNYOURYAN_ADMIN_PASSWORD'], except: [:index, :sitemap]

  def index
    @sites = Site.active
    @message = Message.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title_image
    if @blog.present? && @blog.title_image.present?
      class_string = 'with-title-image'
      if @blog.dark
        class_string += ' dark'

      else
        class_string += ' light'
      end
      class_string
    end
  end
end

app/helpers/blog_helper.rb
module BlogHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end

  def blog_title
    headline = 'Goddamn You Ryan MacInnes - A Kickass Blog for a Kickass Dude'
    if content_for?(:title)
      [content_for(:title), ' - ', headline].join
    else
      headline
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sites_helper.rb
module SitesHelper

  def random_submit_label
    ['Shoot', 'Fuck It', 'Kablamo', 'Awwww yeahhh', 'Whatever', 'Yes, Please', 'Might as well, eh?', 'Sexyness', 'Do It Already'].shuffle.first
  end
end

app/views/admin/base/index.html.slim
coffee:
  jQuery ->
    $('.sort').sortable
      axis: 'y'
      update: ->
        $.post($(this).data('update-url'), $(this).sortable('serialize'))

#admin
  h1 Admin Interface
  =' link_to 'New Site', new_admin_site_path
  =' link_to 'New Blog Post', new_admin_blog_path
  = link_to 'Back to Home', root_path

  h2 Active Sites
  ul#active.sort data-update-url="#{sort_admin_sites_url}"
    - @sites.each do |site|
      = content_tag_for :li, site do
        =' site.name
        =' link_to 'edit', edit_admin_site_path(site)
        = link_to 'deactivate', admin_site_path(site, status: 'inactive'), method: :put

  - if @inactive.any?
    h2 Inactive Sites
    ul
      - @inactive.each do |site|
        li
          =' site.name
          =' link_to 'delete', admin_site_path(site), method: :delete, confirm: 'Are you sure you want to delete this site?'
          = link_to 're-activate', admin_site_path(site, status: 'active'), method: :put

  h2 Blog Posts
  ul
    - @blog.each do |blog|
      li
        =' blog.title
        =' link_to 'show', blog
        =' link_to 'edit', edit_admin_blog_path(blog)
        = link_to 'delete', admin_blog_path(blog), method: :delete, data: { confirm: "Are you sure you want to delete #{blog.title}" }

  h2 Messages
  ul#messages
    - @messages.each do |message|
      li
        h3 = link_to message.name, "mailto:#{message.email}"
        h4 = message.created_at.strftime('%A, %B %-d, %Y')
        div = simple_format truncate(message.body, length: 1000)

app/views/admin/blog/_form.html.slim
= form_for @blog, url: url do |f|

  p = f.text_field :title, placeholder: 'Title'
  p = f.text_field :title_image, placeholder: 'Paste Title Image URL here (optional)'

  p = f.text_area :body, placeholder: 'Write something ya numbskull...'

  p.private
    = f.check_box :private
    ='  f.label :private
    = f.check_box :dark
    = f.label :dark

  p = f.submit

app/views/admin/blog/edit.html.slim
h2 Edit Blog Post
= render partial: 'form', locals: { url: admin_blog_path }

app/views/admin/blog/new.html.slim
h2 New Blog Post
= render partial: 'form', locals: { url: admin_blog_index_path }

app/views/admin/sites/_form.html.slim
= form_for [:admin, @site], html: { multipart: true } do |f|

  p = f.text_field :name, placeholder: 'Name'
  p = f.text_field :url, placeholder: 'External URL'
  p = f.text_area :description, placeholder: 'Describe the goddamned site'

  p.file
    = f.label :photo, '584 x 326px'
    = f.file_field :photo

  p = f.submit

app/views/admin/sites/edit.html.slim
h1 Edit #{@site.name}

= render partial: 'form'

app/views/admin/sites/new.html.slim
h1 New Site

= render partial: 'form'

app/views/blog/_form.html.slim
= form_for @blog, { url: url } do |f|

  p = f.text_field :title, placeholder: 'Title'
  p = f.text_field :title_image, placeholder: 'Paste Title Image URL here (optional)'

  p = f.text_area :body, placeholder: 'Write something ya numbskull...'

  p.private
    = f.check_box :private
    ='  f.label :private
    = f.check_box :dark
    = f.label :dark

  p = f.submit

app/views/blog/show.html.slim
- title @blog.title

- if @blog.title_image.present?
  = image_tag @blog.title_image, class: 'header'
.entry
  header
    h3 = @blog.created_at.strftime("%B #{@blog.created_at.day.ordinalize}, %Y")
    h1 = link_to @blog.title, @blog
  .body = @blog.body.html_safe
  nav
    ul
      - if @next.present?
        li Next: #{link_to @next.title, @next}
      - if @previous.present?
        li Previous: #{link_to @previous.title, @previous}

app/views/layouts/admin.html.slim
doctype html
html
  head
    title GYR Admin
    = stylesheet_link_tag 'admin', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body#admin
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="apple-mobile-web-app-status-bar-style" content="black"
    meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    title New York City and Los Angeles Web Designer and Developer for Websites and Web Apps - God Damn You Ryan MacInnes
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    javascript:
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-36736907-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  body
    = yield

app/views/layouts/blog.html.slim
doctype html
html
  head
    title = blog_title
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    link rel='alternate' type='application/rss+xml' title='Goddamn You Ryan Blog' href="#{blog_index_url(format: :rss)}"
    javascript:
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-36736907-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  body.blog class="#{title_image}"
    header.main
      h1 = link_to 'God Damn You Ryan', blog_index_path
      h2 The Blog of #{link_to 'Ryan MacInnes', root_path}. Web developer and pretty cool dude.
    = yield
    footer
      .container ©#{Time.now.year} #{link_to 'Ryan MacInnes', root_path} #{link_to 'Blog', blog_index_path}

app/views/messages/create.js.erb
$('input.submit').parent().html('<div class=\'notification\'>Well alright then. Ryan will get back to you soon, don\'t you worry.</div>');
$('form.contact input, form.contact textarea').val('');

app/views/sites/admin.html.slim
coffee:
  jQuery ->
    $('.sort').sortable
      axis: 'y'
      update: ->
        $.post($(this).data('update-url'), $(this).sortable('serialize'))

#admin
  h1 Admin Interface
  =' link_to 'New Site', new_site_path
  =' link_to 'New Blog Post', new_blog_path
  = link_to 'Back to Home', root_path

  h2 Active Sites
  ul#active.sort data-update-url="#{sort_sites_url}"
    - Site.active.each do |site|
      = content_tag_for :li, site do
        =' site.name
        =' link_to 'edit', edit_site_path(site)
        = link_to 'deactivate', site_path(site, status: 'inactive'), method: :put

  - if Site.inactive.any?
    h2 Inactive Sites
    ul
      - Site.inactive.each do |site|
        li
          =' site.name
          =' link_to 'delete', site_path(site), method: :delete, confirm: 'Are you sure you want to delete this site?'
          = link_to 're-activate', site_path(site, status: 'active'), method: :put

  h2 Blog Posts
  ul
    - Blog.all.each do |blog|
      li
        =' blog.title
        =' link_to 'show', blog
        =' link_to 'edit', edit_blog_path(blog)
        = link_to 'delete', blog, method: :delete, data: { confirm: "Are you sure you want to delete #{blog.title}" }

  h2 Messages
  ul#messages
    - Message.all.each do |message|
      li
        = message.name
        br
        = link_to message.email, "mailto:#{message.email}"
        br
        = message.body

app/views/sites/index.html.slim
.intro#intro
  h1
    'Goddamn You
    .name Ryan MacInnes

  h2 Pardon my French, I provide the internet sans bullshit.

  nav#sites
    ul
      li = link_to 'Intro', '#intro', class: 'current'
      - @sites.each do |site|
        li = link_to site.name, "##{site.slug}", class: site.slug
      li = link_to 'Contact', '#contact', class: 'contact'

  p
    ' I'm a web designer and programmer from New York City and Los Angeles.
    ' I make websites for myself, or for you.
    ' I work usually using Rails with CSS3, HTML5 and Javascript.
    ' This description of myself is starting to get long and boring already.
    ' Check out my work below, and if you think I'm awesome you should #{link_to 'hire me', '#contact', class: 'hire'}.

    nav#links
      ul
        li = link_to 'Github', 'https://www.github.com/goddamnyouryan', rel: 'external', id: 'github', alt: 'Github'
        li = link_to 'Twitter', 'http://www.twitter.com/goddamnyouryan', rel: 'external', id: 'twitter', alt: 'Twitter'
        li = link_to 'Blog', blog_index_path, rel: 'external', id: 'blog', alt: 'Blog'
        li = link_to 'Email', 'mailto:ryan.macinnes@gmail.com', id: 'email', alt: 'ryan.macinnes@gmail.com'

ul#work
  - @sites.each do |site|
      li id="#{site.slug}"
        = link_to site.url, rel: 'external' do
          .site
            .meta
              h2 = site.name
              p = site.description
            .imac
              = image_tag 'imac.png', width: 633, height: 514
              = image_tag site.photo.url, width: 584, height: 326

  li#contact
    h1 Contact Me
    h2 I promise I'll get back to you. Unless you're a spam robot.
    = form_for @message, remote: true, class: 'contact' do |f|
      p = f.text_field :name, placeholder: 'What\'s your name?'

      p = f.email_field :email, placeholder: 'And your email address?'

      p = f.text_area :body, placeholder: 'What do you want?'

      p = f.submit random_submit_label, class: 'submit', disable_with: 'It\'s a go! Please hold.'

app/views/sites/sitemap.xml.slim
doctype xml
urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'
  url
    loc http://goddamnyouryan.com/
    lastmod = Time.now.strftime('%Y-%m-%d')
    changefreq monthly
    priority 0.8

  url
    loc http://goddamnyouryan.com/blog
    lastmod = Time.now.strftime('%Y-%m-%d')
    changefreq weekly
    priority 0.7

  - Blog.all.each do |blog|
    url
      loc http://goddamnyouryan.com#{blog_path(blog)}
      lastmod = blog.updated_at.strftime('%Y-%m-%d')
      changefreq weekly
      priority 0.5